version: 2.1
orbs:
  aws-cli: circleci/aws-cli@x.y
jobs:
  build:
    machine: # 虛擬機的環境
      node:
        version: 10.16.3 #把剛剛得到的node version填到這裡
      test:
        - npm test  #每一個deploy到github上的commit都會執行npm test
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
      
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              pip install awsebcli
              eb use env-dev --profile circle_ci_test
              eb deploy --profile circle_ci_test
            fi

    
  # build_dev:
  aws-cli-example:
    machine: # 虛擬機的環境
      node:
        version: 10.16.3 #把剛剛得到的node version填到這裡
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circle_ci_test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - aws-cli-example:
          context: aws